//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CungCap
    {
        public int mansx { get; set; }
        public int masanpham { get; set; }
        public Nullable<int> giamua { get; set; }
        public Nullable<int> soluong { get; set; }
        public string donvi { get; set; }
    
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
