//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.CungCaps = new HashSet<CungCap>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public int soluongtonkho { get; set; }
        public int giaban { get; set; }
        public string tinhtrang { get; set; }
        public int maloai { get; set; }
        public string hinhanh { get; set; }
        public System.DateTime ngaycapnhat { get; set; }
        public int hang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CungCap> CungCaps { get; set; }
        public virtual HangXe HangXe { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
